## Project information
site_name: Louis Stefanuto
site_description: Personal website of Louis Stefanuto

## Repository
repo_name: Github
repo_url: https://github.com/LouisStefanuto

theme:
  name: material
  custom_dir: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

plugins:
  - blog:
      archive: false
      categories_name: Post series

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LouisStefanuto
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/louis-stefanuto/

markdown_extensions:
  # nested boxes
  - pymdownx.superfences
  # colored boxes to highlight key points
  - admonition
  # make colored boxes collapsible
  - pymdownx.details
  # for menu fancy grid-organized boxes
  - attr_list
  - md_in_html
  # emojis from Material
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # to add LateX
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - About: about.md
  - Posts:
    - blog/index.md
